### ISSUE TITLE
「ABCとは」のリンク切れ

### ISSUE THREAD

**Issue by prprhyt** [jagsc/ABC2019sConferenceApp#17]
その他のタブにある「ABCとは」のリンクが切れていました。 
あと、ブログについては何も投稿がないので、消すのを検討してもよいかも...  
代わりに学生部のクレジットをいれるとかどうでしょうか

**Comment by Yuki014** [comment]
「ABCとは」のリンクがきれてるのは公式サイトそのものにそのページが反映されてないからです
URLは昨年の「2018s」を「2019s」にしただけなので間違ってないはず

確かにブログも今年は何も書かれないなら消しても良いかも
それは本会の方次第

**Comment by prprhyt** [comment]
ABC運営のweb担当に相談したところ、Aboutページを生やして貰えました。

**Comment by hiyuki2578** [comment]
これリンクつながったしCloseしてもいいのでは？
