### ISSUE TITLE
検索結果をタップすると別のセッションの詳細が表示されてしまう。

### ISSUE THREAD

**Issue by prprhyt** [jagsc/ABC2019sConferenceApp#20]
再現手順

1. 検索タブから検索する(例: セキュリティ)
2. 検索結果をタップする
3. タップしたセッションとは別のセッションの詳細が表示される

**Comment by zyundamochi080** [comment]
検索結果に関係無くtimelineの結果が表示されているみたいです

**Comment by prprhyt** [comment]
https://github.com/jagsc/ABC2019sConferenceApp/blob/ba11dd462a521a1a4690d1a9273d7f887aad8d44/app/src/main/java/jagsc/jp/abc2019Sconferenceapp/Adapter/TimelineAdapter.java#L108

ここっぽい.

**Comment by prprhyt** [comment]
うーん、itemIDあるのになんでpositionで詳細情報を引いているの、なにか理由があるのだろうか。。。

**Comment by prprhyt** [comment]
タイムテーブルの情報、適当なデータ構造で保持しないでMainActivityにデータ流したら、消しているっぽい..?

**Comment by prprhyt** [comment]
あー違うか、保持はしてるっぽい

**Comment by prprhyt** [comment]
今のJSONスキーマでitemIDでセッション情報を引くとO(N)かかるけど、Nが十分に小さいのでその方針でやります...

**Comment by zyundamochi080** [comment]
https://github.com/jagsc/ABC2019sConferenceApp/issues/20#issuecomment-495508388
検索後の画面、上からpositionの値0からになってますね(仕様？)
